backend:
  name: git-gateway
  branch: dev # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: static/img # Media files will be stored in the repo under images/uploads
public_folder: /img


collections:
  - name: "setting" # Used in routes, e.g., /admin/collections/blog
    label: "設定" # Used in the UI
    delete: false
    editor:
      preview: false
    files: 
      - name: "main"
        label: "主設定"
        file: "src/md/setting.md" # The path to the folder where the documents are stored
        fields: # The fields for each document, usually in front matter
          - {label: "公司介紹", name: "description", widget: "text"}
          - {label: "網頁縮略圖", name: "thumbnail", widget: "image"}
          - label: "首頁輪播圖片"
            name: "indexCarousel"
            widget: "list"
            allow_add: true
            field: {label: "圖片", name: "image", widget: "image"}
          - {label: "首頁公司簡介圖片", name: "indexIntroImage", widget: "image"}
          - {label: "關鍵字", name: "keywords", widget: "list", default: ["keyword1", "keyword2", "keyword3"]}
          # 公司電話，地址，等等，可能會更改的所有重要信息
  - name: "services"
    label: "服務項目"
    folder: "src/pages/services"
    slug: "{{slug}}"
    create: true
    delete: true
    fields:
      - {label: "項目名稱", name: "title", widget: "string"}
      - {label: "項目簡介", name: "description", widget: "text"}
      - label: "圖集"
            name: "gallerys"
            widget: "list"
            allow_add: true
            fields: 
              - {label: "標題", name: "title", widget: "string"}
              - label: "圖片組合"
                name: "gallery"
                widget: "list"
                allow_add: true
                field: {label: "圖片", name: "image", widget: "image"}