backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: static/img # Media files will be stored in the repo under images/uploads
public_folder: /img


collections:
  - name: "setting" # Used in routes, e.g., /admin/collections/blog
    label: "主要設定" # Used in the UI
    folder: "src/md/setting" # The path to the folder where the documents are stored
    create: false
    delete: false
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "公司介紹", name: "description", widget: "text"}
      - {label: "網頁縮略圖", name: "thumbnail", widget: "image"}
      - {label: "首頁輪播圖片", name: "indexCarousel", widget: "image"} # TODO 應該做成可添加的列表
      - {label: "首頁公司簡介圖片", name: "indexIntroImage", widget: "image"}
      - {label: "關鍵字", name: "keywords", widget: "list", default: ["keyword1", "keyword2", "keyword3"]}
      # 公司電話，地址，等等，可能會更改的所有重要信息